// EN LA FIESTAS DE CUENCA SE REALIZA TODOS LOS ANOS LOS 10K, SE REQUIERE UN PROGRAMA QUE VERIFIQUE LOS KM RECORRIDOS PARA ESTO SE REQUIERE ESTAS CONDICIONES INGRESANDO LOS COMANDOS DO WHILE



let km = 0;
let totalKM = 10;

do {
    alert (" KM RECORRIDOS " + km)
    km++ // "KM = KM + 1"
} while (km < totalKM);